name: CI
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v5
      - name: Set up JVM
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '23'
      - name: Check
        run: ./gradlew check